apiVersion: apps/v1
kind: Deployment
metadata:
  name: semantis-frontend
  namespace: semantis
  labels:
    app: semantis-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: semantis-frontend
  template:
    metadata:
      labels:
        app: semantis-frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/sathvik-mn/semantis-frontend:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: semantis
spec:
  selector:
    app: semantis-frontend
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
